# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Jifty-DBI-Record-AutoIncremented
version:      0.01
version_from: lib/Jifty/DBI/Record/AutoIncremented.pm
installdirs:  site
requires:
    Jifty::DBI:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
